# Generated by Django 4.2.6 on 2023-10-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('number', models.IntegerField(max_length=11, verbose_name='Номер телефона')),
                ('text', models.TextField(verbose_name='Комментарий ')),
            ],
        ),
    ]
