# Generated by Django 4.2.6 on 2023-10-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='number',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
    ]
